### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by brwnll** [duxet/laravel-rethinkdb#1]
Hey, am starting on a new project and would love to use this package. I see that it hasn't been updated for a few months, and since Laravel 5 just dropped a few weeks ago, not sure where the current status is.

**Comment by duxet** [comment]
Hey. Most important parts of query building and Eloquent should be working. However, it's still missing way to make raw ReQL queries. I am not sure what would be a proper way to do this. Without that feature, it will be hard to make it work fast, as RethinkDB doesn't have query optimizer yet ([#2356](https://github.com/rethinkdb/rethinkdb/issues/2356)) :(

**Comment by thejsj** [comment]
Hey @duxet, just ran into this online. What do you mean by 'raw' ReQL queries? It seems you're using the PHP driver, which is all you need. That's the beautiful part about ReQL. You don't need to write long strings to query the database. Am I missing something? 

In terms of the query optimizer, are you using indexes for your queries? Have you run into any particular bottlenecks? The philosophy behind ReQL is to make the use of indexes explicit, so that the user can know how fast the query will be.

**Comment by zaherg** [comment]
hey @thejsj I think, hopefully am not wrong, @duxet meant that we need a way to execute a raw expression the same we do in laravel query builder ( http://laravel.com/docs/5.0/queries#raw-expressions) .

and what he is trying to do, is not just using the PHP driver, but to build a Laravel specific driver, which will give us the ability to utilize the laravel ORM .

**Comment by duxet** [comment]
@thejsj Hey, thanks for your concern. I was talking with Daniel Mewes about this, and he gave me a hint about getAll/between method. For the moment the only solution would be using raw expressions like @linuxjuggler mentioned.

However i think that Eloquent native methods should be able to use indexes too, but i have no idea how to do do that properly. If i could at least chain getAll methods, or make some advanced queries with OR or AND it would be way easier.

btw. thanks for a shirt and stickers, they are great :+1:
